//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiHat
    {
        public int MaBaiHat { get; set; }
        public string TenBaiHat { get; set; }
        public int MaKhuVuc { get; set; }
        public Nullable<int> MaCaSi { get; set; }
        public string LoiBaiHat { get; set; }
        public System.DateTime NgayDang { get; set; }
        public string HinhAnh { get; set; }
        public string BaiHat1 { get; set; }
    
        public virtual CaSi CaSi { get; set; }
        public virtual KhuVuc KhuVuc { get; set; }
    }
}
