//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public int MaNguoiDung { get; set; }
        public string Email { get; set; }
        public string Matkhau { get; set; }
        public string TenHienThi { get; set; }
        public string DiaChi { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
    }
}
